language: elixir

dist: trusty
sudo: required

services:
  - docker

otp_release: '21.3'

elixir: '1.8'

jobs:
  include:
    - &test
      stage: test
      script: mix test
      before_script:
        - docker-compose up -d
        - ./test/docker/health-check-services.sh
      env: CASSANDRA_VERSION=3

    - <<: *test
      elixir: '1.6'
      otp_release: '19.3'
      env: CASSANDRA_VERSION=3

    - <<: *test
      env: CASSANDRA_VERSION=2.2

    - &test-scylla
      stage: test scylla
      script: mix test --exclude cassandra_specific --exclude encryption
      before_script:
        - docker-compose --file docker-compose.scylladb.yml up -d
        - ./test/docker/health-check-services.sh
      env: SCYLLA_VERSION=2.3.0

    - <<: *test-scylla
      elixir: '1.6'
      otp_release: '19.3'
      env: SCYLLA_VERSION=2.3.0

    - <<: *test-scylla
      env: SCYLLA_VERSION=2.0.0

    - stage: check formatted
      script: mix format --check-formatted
      before_install: skip
      sudo: false
      env: null

stages:
  - check formatted
  - test
  - test scylla
  - test encrypted
